export const ProductPOS = [{
    Name:"riz",
    Categorie:"Portion",
    img: "../Img/Riz.png",
    Prix: 1000,
},
{
    Name:"Banane",
    Categorie:"Portion",
    img: "../Img/banane.png",
    Prix: 1000,
},
{
    Name:"P Frite",
    Categorie:"Portion",
    img: "../Img/Frite.png",
    Prix: 1000,
},
{
    Name:"Burger",
    Categorie:"Burger",
    img: "../Img/burgerPh.png",
    Prix: 2000,
},
{
    Name:"Cheese",
    Categorie:"Burger",
    img: "../Img/Cheese.png",
    Prix: 4000,
},
{
    Name:"Shawarma",
    Categorie:"Shawarma",
    img: "../Img/ShawarmaPh.png",
    Prix: 2000,
},
{
    Name:"Shawarma",
    Categorie:"Shawarma",
    img: "../Img/Shawarma.png",
    Prix: 2500,
},
{
    Name:"poisoon",
    Categorie:"Brochette",
    img: "../Img/BrochettePoisson.png",
    Prix: 1500,
},
{
    Name:"B Poulet",
    Categorie:"Brochette",
    img: "../Img/Brochette Poulet.png",
    Prix: 1500,
},
{
    Name:"B Viande",
    Categorie:"Brochette",
    img: "../Img/BrochetteViande.png",
    Prix: 2000,
},
{
    Name:"PilonPoulet",
    Categorie:"Pilon",
    img: "../Img/PilonPoulet.png",
    Prix: 2000,
},
{
    Name:"Wings",
    Categorie:"Pilon",
    img: "../Img/Wings.png",
    Prix: 2000,
},
{
    Name:"Poulet fri",
    Categorie:"Pilon",
    img: "../Img/PouletFries.png",
    Prix: 2000,
},
{
    Name:"Top",
    Categorie:"Jus",
    img: "../Img/Top.png",
    Prix: 500,
},
{
    Name:"CocaCola",
    Categorie:"Jus",
    img: "../Img/Cocacola.png",
    Prix: 1000,
},
{
    Name:"Cocktail",
    Categorie:"Jus",
    img: "../Img/Fanta.png",
    Prix: 1000,
},
{
    Name:"D'jino P",
    Categorie:"Jus",
    img: "../Img/Pamplemousse.png",
    Prix: 1000,
},
{
    Name:"Sprite",
    Categorie:"Jus",
    img: "../Img/Sprite.png",
    Prix: 1500,
},
{
    Name:"Orangina",
    Categorie:"Jus",
    img: "../Img/Orangina.png",
    Prix: 1500,
},
{
    Name:"Sumol",
    Categorie:"Jus",
    img: "../Img/Sumol.png",
    Prix: 1500,
},
];